CREATE TABLE USERS
(
    ID VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BALANCE DECIMAL NOT NULL
);

CREATE TABLE USER_TRANSACTIONS
(
    USER_ID  VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(100) NOT NULL,
    AMOUNT   DECIMAL      NOT NULL
);

CREATE TABLE ITEMS
(
    ID VARCHAR(100) NOT NULL,
    PRICE DECIMAL NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE ITEM_RESERVATIONS
(
    ITEM_ID VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(255)
);

CREATE TABLE ORDERS
(
    ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    ITEM VARCHAR(100) NOT NULL,
    STATUS VARCHAR(30) NOT NULL
);
